sudo: true
language: python
matrix:
  include:
    - python: "3.5"
before_install:
  - "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk poppler-utils latex-xcolor latex-beamer texlive-xetex"
install:
  - echo Nothing extra to install
script:
  - export TEXMFLOCAL=./texmf
  - make
